apiVersion: v1
kind: ReplicationController
metadata:
  name: discord-bot-build
spec:
  replicas: 1
  selector:
    app: discord-bot-build
  template:
    metadata:
      labels:
        app: discord-bot-build
      name: discord-bot-build
    spec:
      containers:
        - image: cherkim/discord-bot:demo
          imagePullPolicy: Always
          name: discord-bot-build